### ISSUE TITLE
Server Binaries

### ISSUE THREAD

**Issue by ElCapor** [bustersky13/kogama-version-tracker#1]
Is it possible to get server binaries of kogama ?

**Comment by bustersky13** [comment]
I believe they are stored in a private repository so no

**Comment by ElCapor** [comment]
i actually find out they use photon sdk 2.5 for old versions , do you think there's a way to find it ?

**Comment by gustmnds** [comment]
I don't believe that they would provide the server binaries for standalone download, as it wouldn't be logical. The most feasible approach might be to reverse engineer KoGaMa and recreate the server from scratch

**Comment by bustersky13** [comment]
I don’t believe that they would provide the server binaries for standalone download, as it wouldn’t be logical. The most feasible approach might be to reverse engineer KoGaMa and rebuild the server from the ground up

**Comment by ElCapor** [comment]
Yeah i think that's doable for new versions , they base themselves on photon sdk as i said , which is freely avaliable on the internet
